adopt_a_friend/adopt_a_friend/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import *
from users.views import *
from pets.views import *
from staff.views import *
from donation.views import *
from videochat.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('videochat.urls')),
    path('verification/', include('verify_email.urls')),	
    path('', include("users.urls")),
    path('', include("pets.urls")),
    path('', include("staff.urls")),
    path('', include("donation.urls")),
    path('', include("videochat.urls")),
    path('', include('chat.urls'))
]     

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

adopt_a_friend/chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('chat/<str:applicationId>', views.home, name='chat'),
    path('<str:room>/', views.room, name='room'),
    path('chat/checkview/<str:applicationId>', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

adopt_a_friend/pets/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('pet_profile/<str:slug>-<str:petId>/', views.pet_profile, name='pet_profile'),
    path('adoptme/', views.pet_page, name='pet_page'),
    path('application/<str:slug>/', views.application, name='application'),
    path('submitted/', views.submitted, name='submitted'),
    path('already-submitted/', views.application_duplication, name='application_duplication'),
    path('application-limit-exceeded/', views.submission_exceeded, name='submission_exceeded'),
]

adopt_a_friend/pets/models.py
from django.db import models
from users.models import Users
from django.db.models import F
from django.utils.text import slugify
from django.urls import reverse
from django.utils import timezone
from PIL import Image

COLOR_CHOICES = (
    ('Black', 'Black'),
    ('White', 'White'),
    ('Gray', 'Gray'),
    ('Brown', 'Brown'),
    ('Orange', 'Orange'),
    ('Cream', 'Cream'),
    ('Bi-color', 'Bi-color'),
    ('Tricolor', 'Tricolor')
)

PERSONALITY_CHOICES = (
    ('Playful', 'Playful'),
    ('Cuddly', 'Cuddly'),
    ('Energetic', 'Energetic'),
    ('Laid_back', 'Laid-back'),
    ('Curious', 'Curious'),
    ('Social', 'Social'),
    ('Independent', 'Independent'),
    ('Shy/Timid', 'Shy/Timid'),
    ('Bold/Confident', 'Bold/Confident'),
    ('Intelligent', 'Intelligent'),
    ('Mischievous', 'Mischievous'),
    ('Reserved', 'Reserved'),
    ('Protective', 'Protective'),
    ('Adventurous', 'Adventurous'),
    ('Affectionate', 'Affectionate'),
    ('Patient', 'Patient'),
    ('Stubborn', 'Stubborn'),
    ('Gentle', 'Gentle'),
    ('Sociable', 'Sociable'),
    ('Talkative', 'Talkative'),
)

GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other')
)

PET_AGE_CHOICES = (
    ('Puppy/Kitten', 'Puppy/Kitten'),
    ('Young', 'Young'),
    ('Adult', 'Adult'),
    ('Senior', 'Senior')
)

ANIMAL_TYPES_CHOICES = (
    ('Dog', 'Dog'),
    ('Cat', 'Cat'),
    ('Others', 'Others')
)

PET_SIZE_CHOICES = (
    ('Extra Small', 'Extra Small'),
    ('Small', 'Small'),
    ('Medium', 'Medium'),
    ('Large', 'Large')
)

HEALTH_CONDITIONS = (
    ('Healthy', 'Healthy'),
    ('With Disease/Illness', 'With Disease/Illness'),
    ('Chronic Condition', 'Chronic Condition'),
    ('Under Treatment', 'Under Treatment'),
    ('Recovering', 'Recovering'),
    ('Injured', 'Injured'),
    ('Behavioral Issues', 'Behavioral Issues'),
    ('Senior Care', 'Senior Care'),
)

APPLICATION_STATUS = (
    ('Pending', 'Pending'),
    ('Interviewing', 'Interviewing'),
    ('Accepted', 'Accepted'),
    ('On Hold', 'On Hold'),
    ('Rejected', 'Rejected'),
    ('Evaluating', 'Evaluating'),
    ('Completed', 'Completed'),
)

INTERVIEW_MODE = (
    ('Online', 'Online'),
    ('On-site', 'On-site'),
)
def generate_pet_key():
    last_record = Pet.objects.order_by('-petId').first()
    if last_record is not None:
        last_id = int(last_record.petId[3:])  # Extract the numeric part of the petId
        new_id = last_id + 1
    else:
        new_id = 1
    return f'PET{str(new_id).zfill(4)}'

def generate_med_key():
    last_record = Pet.objects.order_by('-medId').first()
    if last_record is not None:
        new_id = F('medId') + 1
    else:
        new_id = 1
    return f'MED{str(new_id).zfill(4)}'

def generate_application_key():
    last_record = Application.objects.order_by('-applicationId').first()
    if last_record is not None:
        last_id = int(last_record.applicationId[3:])  # Extract the numeric part of the petId
        new_id = last_id + 1
    else:
        new_id = 1
    return f'APP{str(new_id).zfill(4)}'

class Pet(models.Model):
    petId = models.CharField(max_length=10, default=generate_pet_key, primary_key=True, unique=True)
    petName = models.CharField(max_length=50, null=False, blank=False, unique=True)
    animalType = models.CharField(max_length=20, choices=ANIMAL_TYPES_CHOICES, null=False, blank=False)
    breed = models.CharField(max_length=50, null=False, blank=False)
    petAge = models.CharField(max_length=50, null=False, blank=False, choices=PET_AGE_CHOICES)
    petGender = models.CharField(max_length=20, choices=GENDER_CHOICES, null=False, blank=False, default="")
    petSize = models.CharField(max_length=20, choices=PET_SIZE_CHOICES, null=False, blank=False)
    petColor = models.CharField(max_length=20, choices=COLOR_CHOICES, null=False, blank=False, default="")
    petDescription = models.TextField(max_length=500, blank=True, null=True)
    petPersonality = models.CharField(max_length=50, choices=PERSONALITY_CHOICES, blank=False, null=False, default="")
    dateAcquired = models.DateField(blank=False, null=False, default=timezone.now)
    isTrained = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, blank=True)
    
    def get_absolute_pet_url(self):
        return reverse("pet_profile", kwargs={"slug": self.slug, "petId": str(self.petId)})
    
    def get_absolute_pet_url_for_update(self):
        return reverse("edit_pet", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(f"{self.petName}")
        super(Pet, self).save(*args, **kwargs)

class PetImage(models.Model):
    petId = models.ForeignKey('Pet', null=False, blank=False, on_delete=models.CASCADE)
    petImage = models.ImageField(upload_to='static/pet_pics')

    def save(self, *args, **kwargs):
        try:
            this = PetImage.objects.get(id=self.id)
            if this.petImage != self.petImage:
                this.petImage.delete(save=False)
        except PetImage.DoesNotExist:
            pass

        super(PetImage, self).save(*args, **kwargs)

class PetMedical(models.Model):
    petId = models.OneToOneField(Pet, null=False, blank=False, on_delete=models.CASCADE)
    petWeight = models.IntegerField(blank=False, null=False)
    isVaccinated = models.BooleanField()
    isNeutered_or_Spayed = models.BooleanField()
    healthCondition = models.CharField(max_length=30, null=False, choices=HEALTH_CONDITIONS)
    disease = models.CharField(max_length=100, null=False)
    comment = models.TextField(max_length=500, blank=True, null=True)

class Application(models.Model):
    applicationId = models.CharField(max_length=10, default=generate_application_key, primary_key=True, unique=True)
    pet = models.ForeignKey(Pet, null=False, on_delete=models.CASCADE)
    user = models.ForeignKey(Users, null=False, on_delete=models.CASCADE)
    adopteeFirstName = models.CharField(max_length=50, null=False, blank=False)
    adopteeLastName = models.CharField(max_length=50, null=False, blank=False)
    adopteeHomeAddress = models.CharField(max_length=300, null=False, blank=False)
    adopteeContactNum = models.CharField(max_length=15, null=False, blank=False)
    picture = models.ImageField(blank=False, null=False, upload_to='static/application_pics', default="static/default.png")
    status = models.CharField(max_length=50, choices=APPLICATION_STATUS ,null=False, blank=False, default="Pending")
    preferredModeOfInterview =  models.CharField(max_length=50, choices=INTERVIEW_MODE ,null=False, blank=False, default="")
    modeOfInterview =  models.CharField(max_length=50, choices=INTERVIEW_MODE ,null=False, blank=False, default="")
    staffComment = models.TextField(max_length=300, null=False, blank=True, default='')
    interviewDate = models.DateField(null=True, blank=True)
    interviewTime = models.TimeField(null=True, default=None, blank=True)
    inPersonVisitDate = models.DateField(null=True, blank=True)
    inPersonVisitTime = models.TimeField(null=True, default=None, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

class HousePicture(models.Model):
    applicationId = models.ForeignKey(Application, null=False, on_delete=models.CASCADE)
    housePicture = models.ImageField(blank=False, null=False, upload_to='static/application_pics')

class IdPicture(models.Model):
    applicationId = models.ForeignKey(Application, null=False, on_delete=models.CASCADE)
    validIdPicture = models.ImageField(blank=False, null=False, upload_to='static/application_pics')

class CondoAgreement(models.Model):
    applicationId = models.ForeignKey(Application, null=False, on_delete=models.CASCADE)
    condoAgreement = models.FileField(upload_to='static/application_files', null=True, blank=True)

adopt_a_friend/pets/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .recommendation import recommend_pets
from users.models import Preference
from django.utils import timezone


# Create your views here.

def pet_profile(request, petId, slug):
    pet = get_object_or_404(Pet, petId=petId, slug=slug)
    medical = get_object_or_404(PetMedical, petId=pet)
    images = PetImage.objects.filter(petId=pet)

    context = {
            'pet': pet,
            'medical': medical,
            'images': images,
        }

    return render(request, 'pets/pet_profile.html', context)

from .recommendation import recommend_pets

def pet_page(request):
    query = request.GET.get('q')
    pets = Pet.objects.all().order_by('petId')
    recommended_pets = []

    if request.user.is_authenticated:
        try:
            # Try to get the user's preferences
            user_pref = Preference.objects.get(adopter=request.user)
            # Get recommended pets for the authenticated user
            recommended_pets = recommend_pets(request.user)
        except Preference.DoesNotExist:
            # Handle the case where the user has no preferences
            pass

    if query:
        # Filter pets based on the search query
        pets = pets.filter(
            Q(petName__icontains=query) |
            Q(animalType__icontains=query) |
            Q(breed__icontains=query) |
            Q(petAge__icontains=query) |
            Q(petGender__icontains=query) 
        )

    return render(request, 'pets/adoptme.html', {'pets': pets, 'recommended_pets': recommended_pets})

@login_required
def application(request, slug):
    pet = get_object_or_404(Pet, slug=slug)
    user = request.user

    existing_application = Application.objects.filter(pet=pet, user=user).first()
    if existing_application:
        # You can redirect to a page indicating that the user has already applied for this pet
        return redirect('application_duplication')
    
    week_ago = timezone.now() - timezone.timedelta(weeks=1)
    user_applications_last_week = Application.objects.filter(user=user, created_at__gte=week_ago).count()

    if user_applications_last_week >= 2:
        # You can redirect to a page indicating that the user has reached the limit for the week
        return redirect('submission_exceeded')

    if request.method == 'POST':
        application_form = ApplicationForm(request.POST)
        house_picture_formset = HousePictureFormSet(request.POST, request.FILES, prefix='house_picture')
        id_picture_formset = IdPictureFormSet(request.POST, request.FILES, prefix='id_picture')
        condo_agreement_form = CondoAgreementForm(request.POST, request.FILES)

        if (
            application_form.is_valid()
            and house_picture_formset.is_valid()
            and id_picture_formset.is_valid()
            and condo_agreement_form.is_valid()
        ):
            # Save the main application form
            application_instance = application_form.save(commit=False)
            application_instance.pet = pet
            application_instance.user = user
            application_instance.save()

            # Save the related forms in the formsets
            house_picture_formset.instance = application_instance
            house_picture_formset.save()

            id_picture_formset.instance = application_instance
            id_picture_formset.save()

            # Save the condo agreement form if provided
            if request.FILES.get('condoAgreement'):
                condo_agreement_instance = condo_agreement_form.save(commit=False)
                condo_agreement_instance.applicationId = application_instance
                condo_agreement_instance.save()

            # Redirect to a success page or any other desired page
            return redirect('submitted')  # Replace 'success_page' with the actual URL or name of the success page

    else:
        # Pass the logged-in user to the form
        application_form = ApplicationForm(initial={'adopteeFirstName': user.first_name,
                                                    'adopteeLastName': user.last_name,
                                                    'adopteeHomeAddress': user.home_address,
                                                    'adopteeContactNum': user.contact_num})
        house_picture_formset = HousePictureFormSet(prefix='house_picture')
        id_picture_formset = IdPictureFormSet(prefix='id_picture')
        condo_agreement_form = CondoAgreementForm()

    context = {
        'pet': pet,
        'user': user,
        'application_form': application_form,
        'house_picture_formset': house_picture_formset,
        'id_picture_formset': id_picture_formset,
        'condo_agreement_form': condo_agreement_form,
    }

    return render(request, 'pets/application.html', context)

@login_required
def submitted(request):
    return render(request, 'pets/application_submitted_successfuly.html')

@login_required
def submission_exceeded(request):
    return render(request, 'pets/application_limit_exceeded.html')

@login_required
def application_duplication(request):
    return render(request, 'pets/application_already_submitted.html')

adopt_a_friend/pets/templates/pets/adoptme.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} Pets {% endblock %}

{% block scripts %} 
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% endblock %}

{% block content %}
<div class="my-28" style="font-family: 'Imprima';">
    <div class="grid grid-cols-5 mx-auto max-w-screen-xl justify-center gap-x-10 gap-y-8">
        <div class="mt-3 shadow-lg col-span-5">
            <div class="mx-auto max-w-screen-xl h-20 rounded-xl flex justify-between" style="background-color: #f89651;">
                <h1 class="py-7 pl-8 text-xl text-white text-shadows font-bold">Adopt and Give Them Home</h1>
                <form method="GET" action="{% url 'pet_page' %}" class="py-5 pr-6">
                    <input type="text" name="q" placeholder="Search pets..." class="p-2 border border-gray-300 rounded">
                    <button type="submit" class="shadow-inner transition ease-in-out delay-150 font-semibold text-white px-5 py-2 rounded-md hover:-translate-y-1 hover:scale-110 duration-300 bg-amber-900">Search</button>
                </form>
            </div>
        </div>
        
        {% if request.GET.q %}
        {% if pets %}
        {% for pet in pets %}
            <div class="w-60 h-auto p-3 flex flex-col rounded-2xl shadow-lg mt-3" style="background-color: #f89651;" id="{{pet.petId}}">
                <div class="h-48 bg-white rounded-xl" style="background-image: url('{{ pet.petimage_set.first.petImage.url }}'); background-size: cover;"></div>
                <div class="flex flex-col gap-2">
                    <div class="flex flex-row justify-between pt-2">
                        <div class="flex flex-col">
                            <span class="text-xl font-bold text-white">{{pet.petName}}</span>
                        </div>
                        <span class="font-bold text-white">{{pet.animalType}}</span>
                    </div>
                    <div class="text-white">
                        <p class="text-justify">{{pet.petDescription|truncatechars:50}}</p>
                    </div>
                    <div class="flex justify-end">
                        <a href="{% url 'pet_profile' pet.slug pet.petId %}">
                            <button type="" class="shadow-inner transition ease-in-out delay-150 font-semibold text-white px-5 py-2 rounded-md hover:-translate-y-1 hover:scale-100 duration-300 bg-amber-900">Adopt Me</button>
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p class="text-3xl font-bold col-span-5">No results found for the search query.</p>
    {% endif %}
        {% else %}

            {% if user.is_authenticated %}
                {% if recommended_pets %}
                    <div class="col-span-5">
                        <h1 class="text-4xl font-bold">Recommended For You</h1>
                    </div>
                    {% for pet in recommended_pets%}
                        <div class="w-60 h-auto p-3 flex flex-col rounded-2xl shadow-lg mt-3" style="background-color: #f89651;" id="{{pet.petId}}">
                            <div class="h-48 bg-white rounded-xl" style="background-image: url('{{ pet.petimage_set.first.petImage.url }}'); background-size: cover;"></div>
                            <div class="flex flex-col gap-2">
                                <div class="flex flex-row justify-between pt-2">
                                    <div class="flex flex-col">
                                    <span class="text-xl font-bold text-white">{{pet.petName}}</span>
                                    </div>
                                    <span class="font-bold  text-white">{{pet.animalType}}</span>
                                </div>
                                <div class="text-white">
                                    <p class="text-justify">{{pet.petDescription|truncatechars:50}}</p>
                                </div>
                                <div class="flex justify-end"> <!-- Use flex utility class to align items to the end -->
                                    <a href="{% url 'pet_profile' pet.slug pet.petId %}">
                                        <button type="" class="shadow-inner transition ease-in-out delay-150 font-semibold text-white px-5 py-2 rounded-md hover:-translate-y-1 hover:scale-100 duration-300 bg-amber-900">Adopt Me</button>
                                    </a>
                                </div>             
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
            <div class="col-span-5 flex items-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="mr-3 w-12 h-12" viewBox="0 0 256 256"><path fill="currentColor" d="m239.71 125l-16.42-88a16 16 0 0 0-19.61-12.58l-.31.09L150.85 40h-45.7L52.63 24.56l-.31-.09a16 16 0 0 0-19.61 12.58L16.29 125a15.77 15.77 0 0 0 9.12 17.52a16.26 16.26 0 0 0 6.71 1.48a15.48 15.48 0 0 0 7.88-2.16V184a40 40 0 0 0 40 40h96a40 40 0 0 0 40-40v-42.15a15.5 15.5 0 0 0 7.87 2.16a16.31 16.31 0 0 0 6.72-1.47a15.77 15.77 0 0 0 9.12-17.54ZM32 128l16.43-88L90.5 52.37Zm144 80h-40v-12.69l13.66-13.65a8 8 0 0 0-11.32-11.32L128 180.69l-10.34-10.35a8 8 0 0 0-11.32 11.32L120 195.31V208H80a24 24 0 0 1-24-24v-60.89L107.92 56h40.15L200 123.11V184a24 24 0 0 1-24 24Zm48-80l-58.5-75.63L207.57 40L224 128Zm-120 12a12 12 0 1 1-12-12a12 12 0 0 1 12 12Zm72 0a12 12 0 1 1-12-12a12 12 0 0 1 12 12Z"/></svg>
                <h1 class="text-4xl font-bold">Our Dogs</h1>
            </div>
            {% for pet in pets %}
                {% if pet.animalType == "Dog"%}
                    <div class="w-60 h-auto p-3 flex flex-col rounded-2xl shadow-lg mt-3" style="background-color: #f89651;" id="{{pet.petId}}">
                        <div class="h-48 bg-white rounded-xl" style="background-image: url('{{ pet.petimage_set.first.petImage.url }}'); background-size: cover;"></div>
                        <div class="flex flex-col gap-2">
                            <div class="flex flex-row justify-between pt-2">
                                <div class="flex flex-col">
                                <span class="text-xl font-bold text-white">{{pet.petName}}</span>
                                </div>
                                <span class="font-bold  text-white">{{pet.animalType}}</span>
                            </div>
                            <div class="text-white">
                                <p class="text-justify">{{pet.petDescription|truncatechars:50}}</p>
                            </div>
                            <div class="flex justify-end"> <!-- Use flex utility class to align items to the end -->
                                <a href="{% url 'pet_profile' pet.slug pet.petId %}">
                                    <button type="" class="shadow-inner transition ease-in-out delay-150 font-semibold text-white px-5 py-2 rounded-md hover:-translate-y-1 hover:scale-100 duration-300 bg-amber-900">Adopt Me</button>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

            <div class="col-span-5 flex item-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="mr-3 w-12 h-12" viewBox="0 0 256 256"><path fill="currentColor" d="M96 140a12 12 0 1 1-12-12a12 12 0 0 1 12 12Zm76-12a12 12 0 1 0 12 12a12 12 0 0 0-12-12Zm60-80v88c0 52.93-46.65 96-104 96S24 188.93 24 136V48a16 16 0 0 1 27.31-11.31c.14.14.26.27.38.41L69 57a111.22 111.22 0 0 1 118.1 0l17.21-19.9c.12-.14.24-.27.38-.41A16 16 0 0 1 232 48Zm-16 0l-21.56 24.8a8 8 0 0 1-10.81 1.2A88.86 88.86 0 0 0 168 64.75V88a8 8 0 1 1-16 0V59.05a97.43 97.43 0 0 0-16-2.72V88a8 8 0 1 1-16 0V56.33a97.43 97.43 0 0 0-16 2.72V88a8 8 0 1 1-16 0V64.75A88.86 88.86 0 0 0 72.37 74a8 8 0 0 1-10.81-1.17L40 48v88c0 41.66 35.21 76 80 79.67v-20.36l-13.66-13.66a8 8 0 0 1 11.32-11.31L128 180.68l10.34-10.34a8 8 0 0 1 11.32 11.31L136 195.31v20.36c44.79-3.69 80-38 80-79.67Z"/></svg>
                <h1 class="text-4xl font-bold">Our Cats</h1>
            </div>
            {% for pet in pets %}
                {% if pet.animalType == "Cat"%}
                    <div class="w-60 h-auto p-3 flex flex-col rounded-2xl shadow-lg mt-3" style="background-color: #f89651;" id="{{pet.petId}}">
                        <div class="h-48 bg-white rounded-xl" style="background-image: url('{{ pet.petimage_set.first.petImage.url }}'); background-size: cover;"></div>
                        <div class="flex flex-col gap-2">
                            <div class="flex flex-row justify-between pt-2">
                                <div class="flex flex-col">
                                <span class="text-xl font-bold text-white">{{pet.petName}}</span>
                                </div>
                                <span class="font-bold  text-white">{{pet.animalType}}</span>
                            </div>
                            <div class="text-white">
                                <p class="text-justify">{{pet.petDescription|truncatechars:50}}</p>
                            </div>
                            <div class="flex justify-end"> <!-- Use flex utility class to align items to the end -->
                                <a href="{% url 'pet_profile' pet.slug pet.petId %}">
                                    <button type="" class="shadow-inner transition ease-in-out delay-150 font-semibold text-white px-5 py-2 rounded-md hover:-translate-y-1 hover:scale-100 duration-300 bg-amber-900">Adopt Me</button>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

            <div class="col-span-5 flex items-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="mr-3 w-12 h-12" viewBox="0 0 14 14"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M1.5 9.5c.552 0 1-.672 1-1.5s-.448-1.5-1-1.5s-1 .672-1 1.5s.448 1.5 1 1.5Zm3-4.5c.552 0 1-.672 1-1.5S5.052 2 4.5 2s-1 .672-1 1.5s.448 1.5 1 1.5Zm5 0c.552 0 1-.672 1-1.5S10.052 2 9.5 2s-1 .672-1 1.5s.448 1.5 1 1.5Zm3 4.5c.552 0 1-.672 1-1.5s-.448-1.5-1-1.5s-1 .672-1 1.5s.448 1.5 1 1.5ZM10 10c0 1.38-1.62 2-3 2s-3-.62-3-2s1-3.5 3-3.5s3 2.12 3 3.5Z"/></svg>
                <h1 class="text-4xl font-bold">Adoptable Pets</h1>
            </div>
            {% for pet in pets %}
            <div class="w-60 h-auto p-3 flex flex-col rounded-2xl shadow-lg mt-3" style="background-color: #f89651;" id="{{pet.petId}}">
                <div class="h-48 bg-white rounded-xl" style="background-image: url('{{ pet.petimage_set.first.petImage.url }}'); background-size: cover;"></div>
                <div class="flex flex-col gap-2">
                    <div class="flex flex-row justify-between pt-2">
                        <div class="flex flex-col">
                        <span class="text-xl font-bold text-white">{{pet.petName}}</span>
                        </div>
                        <span class="font-bold  text-white">{{pet.animalType}}</span>
                    </div>
                    <div class="text-white">
                        <p class="text-justify">{{pet.petDescription|truncatechars:50}}</p>
                    </div>
                    <div class="flex justify-end"> <!-- Use flex utility class to align items to the end -->
                        <a href="{% url 'pet_profile' pet.slug pet.petId %}">
                            <button type="" class="shadow-inner transition ease-in-out delay-150 font-semibold text-white px-5 py-2 rounded-md hover:-translate-y-1 hover:scale-100 duration-300 bg-amber-900">Adopt Me</button>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock %}